//! The authoritative list of configuration parameter paths.
//!
//! Validation requires the provenance list to cover this set exactly: every
//! path present once, and no provenance entry naming a path that is not here.
//! Adding a configuration field without adding it here (and adding provenance
//! for it) is a validation failure, not a silent omission.

/// Every parameter path that must carry provenance.
pub const PARAMETER_PATHS: &[&str] = &[
    "geometry.cylinders",
    "geometry.bore_m",
    "geometry.stroke_m",
    "geometry.connecting_rod_m",
    "geometry.compression_ratio",
    "geometry.firing_order",
    "geometry.published_displacement_m3",
    "geometry.published_stroke_bore_ratio",
    "valvetrain.intake_valves_per_cylinder",
    "valvetrain.exhaust_valves_per_cylinder",
    "valvetrain.intake_valve_close_rad",
    "valvetrain.exhaust_valve_open_rad",
    "injection.rail_pressure_max_pa",
    "injection.amplified_pressure_max_pa",
    "injection.fuel_lower_heating_value_j_per_kg",
    "injection.max_fuel_mg_per_cycle",
    "injection.smoke_limit_afr",
    "combustion.start_of_combustion_rad",
    "combustion.burn_duration_rad",
    "combustion.combustion_efficiency",
    "combustion.burned_gas_cv_j_per_kg_k",
    "combustion.polytropic_compression",
    "combustion.polytropic_expansion",
    "friction.fmep_constant_pa",
    "friction.fmep_peak_pressure_coeff",
    "friction.fmep_piston_speed_coeff_pa_s_per_m",
    "friction.fmep_piston_speed_sq_coeff",
    "air_path.intake_manifold_pressure_pa",
    "air_path.intake_manifold_temperature_k",
    "air_path.exhaust_manifold_pressure_pa",
    "air_path.crankcase_pressure_pa",
    "air_path.gas_constant_j_per_kg_k",
    "air_path.volumetric_efficiency",
    "governor.idle_target_rpm",
    "governor.idle_p_gain_mg_per_rad_s",
    "governor.idle_i_gain_mg_per_rad",
    "governor.idle_integral_limit_mg",
    "governor.overspeed_taper_start_rpm",
    "governor.overspeed_cutoff_rpm",
    "load.accessory_torque_constant_nm",
    "load.accessory_torque_per_rad_s",
    "load.max_external_load_nm",
    "load.starter_torque_nm",
    "load.starter_cutout_rpm",
    "inertia.rotating_inertia_kg_m2",
    "inertia.complete_engine_mass_kg",
    "limits.max_combustion_pressure_pa",
    "limits.max_rpm",
    "limits.max_gas_temperature_k",
    "solver.fixed_step_s",
    "solver.max_steps_per_batch",
    "audio.reference_spl_db",
    "audio.exhaust_gain",
    "rated.max_power_w",
    "rated.max_power_hp",
    "rated.max_torque_nm",
];
